project_id = "ucotwtuclnpsrmbbvrsk"

[functions.verify-access-code]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.create-provider-user]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = false

[functions.regenerate-access-code]
verify_jwt = false

[functions.dispatch-scheduled-announcements]
verify_jwt = false

[functions.send-announcement-push]
verify_jwt = false

[functions.send-message-push]
verify_jwt = false

