import { supabase } from '@/integrations/supabase/client';
import type { Tables } from '@/integrations/supabase/types';

export type AttendeeRow = Tables<'attendees'>;

export interface AttendeeWithServices extends AttendeeRow {
  servicesCount: number;
}

export interface CreateAttendeeData {
  event_id: string;
  full_name: string;
  email: string;
  specialty?: string;
  institution?: string;
  registration_status?: string;
}

export interface AttendeeCounts {
  total: number;
  confirmed: number;
  pending: number;
}

export const adminAttendeesService = {
  getAttendees: async (
    eventId: string,
    search?: string,
    statusFilter?: string,
  ): Promise<AttendeeWithServices[]> => {
    let query = supabase
      .from('attendees')
      .select('*')
      .eq('event_id', eventId)
      .is('deleted_at', null)
      .order('created_at', { ascending: false });

    if (statusFilter && statusFilter !== 'all') {
      query = query.eq('registration_status', statusFilter);
    }

    if (search) {
      query = query.or(
        `full_name.ilike.%${search}%,email.ilike.%${search}%,credential_code.ilike.%${search}%`,
      );
    }

    const { data, error } = await query;
    if (error) throw new Error(error.message);

    // Get services count per attendee
    const attendeeIds = (data ?? []).map((a) => a.id);
    let servicesCounts: Record<string, number> = {};

    if (attendeeIds.length > 0) {
      const { data: services } = await supabase
        .from('attendee_services')
        .select('attendee_id')
        .in('attendee_id', attendeeIds);

      if (services) {
        servicesCounts = services.reduce(
          (acc, s) => {
            acc[s.attendee_id] = (acc[s.attendee_id] || 0) + 1;
            return acc;
          },
          {} as Record<string, number>,
        );
      }
    }

    return (data ?? []).map((a) => ({
      ...a,
      servicesCount: servicesCounts[a.id] ?? 0,
    }));
  },

  getCounts: async (eventId: string): Promise<AttendeeCounts> => {
    const [totalRes, confirmedRes, pendingRes] = await Promise.all([
      supabase
        .from('attendees')
        .select('id', { count: 'exact', head: true })
        .eq('event_id', eventId)
        .is('deleted_at', null),
      supabase
        .from('attendees')
        .select('id', { count: 'exact', head: true })
        .eq('event_id', eventId)
        .eq('registration_status', 'confirmed')
        .is('deleted_at', null),
      supabase
        .from('attendees')
        .select('id', { count: 'exact', head: true })
        .eq('event_id', eventId)
        .eq('registration_status', 'pending')
        .is('deleted_at', null),
    ]);

    return {
      total: totalRes.count ?? 0,
      confirmed: confirmedRes.count ?? 0,
      pending: pendingRes.count ?? 0,
    };
  },

  createAttendee: async (data: CreateAttendeeData): Promise<AttendeeRow> => {
    // credential_code is auto-generated by trigger
    const { data: attendee, error } = await supabase
      .from('attendees')
      .insert({
        event_id: data.event_id,
        full_name: data.full_name,
        email: data.email,
        specialty: data.specialty || null,
        institution: data.institution || null,
        registration_status: data.registration_status || 'confirmed',
        credential_code: '', // Will be overwritten by trigger
      })
      .select()
      .single();

    if (error) throw new Error(error.message);
    return attendee;
  },

  bulkCreateAttendees: async (
    eventId: string,
    rows: { full_name: string; email: string; specialty?: string; institution?: string }[],
  ): Promise<{ inserted: number; errors: number }> => {
    const inserts = rows.map((r) => ({
      event_id: eventId,
      full_name: r.full_name,
      email: r.email,
      specialty: r.specialty || null,
      institution: r.institution || null,
      registration_status: 'confirmed' as const,
      credential_code: '', // trigger handles it
    }));

    const { data, error } = await supabase.from('attendees').insert(inserts).select('id');

    if (error) throw new Error(error.message);
    return { inserted: data?.length ?? 0, errors: rows.length - (data?.length ?? 0) };
  },

  deleteAttendee: async (attendeeId: string): Promise<void> => {
    const { error } = await supabase
      .from('attendees')
      .update({ deleted_at: new Date().toISOString() })
      .eq('id', attendeeId);

    if (error) throw new Error(error.message);
  },

  getAttendeeDetail: async (attendeeId: string) => {
    const [attendeeRes, servicesRes, checkinsRes] = await Promise.all([
      supabase.from('attendees').select('*').eq('id', attendeeId).single(),
      supabase
        .from('attendee_services')
        .select('*, service_catalog:service_catalog_id(name, service_type)')
        .eq('attendee_id', attendeeId),
      supabase
        .from('attendee_checkins')
        .select('*, event_activities:activity_id(title, scheduled_date)')
        .eq('attendee_id', attendeeId)
        .order('checked_in_at', { ascending: false }),
    ]);

    if (attendeeRes.error) throw new Error(attendeeRes.error.message);

    return {
      attendee: attendeeRes.data,
      services: servicesRes.data ?? [],
      checkins: checkinsRes.data ?? [],
    };
  },

  regenerateCode: async (attendeeId: string): Promise<string> => {
    const { data, error } = await supabase.rpc('create_attendee_credential', {
      _attendee_id: attendeeId,
    });
    if (error) throw new Error(error.message);
    return data as string;
  },
};
